name: mkbsd

on:
    push:
    workflow_dispatch:

jobs:
  mkbhd:
    name: download
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
            repository: 'korewaChino/mkbsd-rs'

      - name: Get datetime
        id: datetime
        run: echo "datetime=$(date --iso-8601=seconds --utc)" >> $GITHUB_OUTPUT
            
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo run --release
      - run: tar czf downloads.tar.gz downloads

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: downloads.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.datetime.outputs.datetime }}
          draft: false
          prerelease: false
          makeLatest: true
